name: Reusable Test Workflow

on:
    workflow_call:
        inputs:
            branch:
                required: true
                type: string
            run-test:
                required: true
                type: boolean
        secrets:
            NPM_TOKEN:
                required: true
            FA_TOKEN:
                required: true

jobs:
    test:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.18.1]
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3.2.0
              with:
                  ref: ${{ inputs.branch }}
            # If package-lock.json does not change, the node modules are used from the cache to improve the speed

            - name: Cache node modules
              uses: actions/cache@v3.0.11
              id: npm-cache
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Node ${{ matrix.node-version }}
              uses: actions/setup-node@v3.5.1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: npm set config for FA
              run: npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FA_TOKEN }}"

            - name: npm set config for NPM
              run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

            - name: npm install
              run: npm ci

            - name: lint
              id: lint
              run: npm run lint

            # temporarily skip prettier tests due to different results on local machine and in CI workflow
            # - name: prettier
            #  id: prettier
            #  run: npm run checkPrettier

            - name: tests
              if: ${{ inputs.run-test }}
              id: test
              run: npm run test:ci

            - name: npm run build
              run: npm run build:prod
