name: Reusable Build Workflow

on:
    workflow_call:
        inputs:
            branch:
                required: true
                type: string
            # needs to match the folder name in the dist directory
            # should be equal with project name
            output-name:
                required: true
                type: string
            is-prerelease:
                required: true
                type: boolean
        secrets:
            NPM_TOKEN:
                required: true
            FA_TOKEN:
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.18.1]
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3.2.0
              with:
                ref: ${{ inputs.branch }}
            # If package-lock.json does not change, the node modules are used from the cache to improve the speed

            - name: Cache node modules
              uses: actions/cache@v3.0.11
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-

            - name: Node ${{ matrix.node-version }}
              uses: actions/setup-node@v3.5.1
              with:
                node-version: ${{ matrix.node-version }}

            - name: npm set config for FA
              run: npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FA_TOKEN }}"

            - name: npm set config for NPM
              run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

            - name: npm install
              run: npm ci

            - name: npm run build
              run: npm run build:prod

            - name: bump npm version
              run: npm version patch --no-git-tag-version

            - name: Read package.json version
              uses: martinbeentjes/npm-get-version-action@v1.2.3
              id: package-version
              
            - name: Print extracted version
              run: echo "New version ${{ steps.package-version.outputs.current-version }}"

            - name: Add version and build info to index.html
              run: |
                # adding the last commit as comment in index.html
                printf '<!-- App Version: %s-%s -->\n' "${{ steps.package-version.outputs.current-version }}" "${{ inputs.branch }}" >> dist/${{ inputs.output-name }}/index.html
                printf '<!-- Build Date: %s -->\n' "$(TZ='Europe/Zurich' date)" >> dist/${{ inputs.output-name }}/index.html
            
            - uses: vimtor/action-zip@v1.1
              with:
                  files: dist/${{ inputs.output-name }}/
                  dest: ${{ inputs.output-name }}-${{ inputs.branch }}.zip

            - name: Create Release
              id: create_release
              # more specific than v1
              uses: ncipollo/release-action@v1.12.0
              with:
                  tag: ${{ steps.package-version.outputs.current-version }}-${{ inputs.branch }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  name: Release ${{ steps.package-version.outputs.current-version }}-${{ inputs.branch }}
                  draft: false
                  prerelease: ${{ inputs.is-prerelease }}
                  generateReleaseNotes: true

            - name: Upload Release Asset
              id: upload-release-asset
              # more specific than v1
              uses: softprops/action-gh-release@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  # upload_url: ${{ steps.create_release.outputs.upload_url }}
                  # asset_path: ./${{ inputs.output-name }}-${{ inputs.branch }}.zip
                  files: "./dist/*"
                  name: ${{ inputs.output-name }}-${{ inputs.branch }}.zip
                  tag_name: ${{ steps.package-version.outputs.current-version }}-${{ inputs.branch }}
                  # asset_content_type: application/zip

            - name: cleanup zip file
              run: rm -f ./${{ inputs.output-name }}-${{ inputs.branch }}.zip

            - name: create commit
              uses: stefanzweifel/git-auto-commit-action@v4.16.0
              with:
                  commit_message: ${{ steps.package-version.outputs.current-version }}
                  branch: ${{ inputs.branch }}
