name: Reusable ZIP and Release Workflow

on:
    workflow_call:
        inputs:
            branch:
                required: true
                type: string
            # should be equal with project name
            output-name:
                required: true
                type: string
            files:
              required: true
              type: string

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.16.3]
        steps:
          - uses: actions/checkout@v3.2.0

          - name: Get Time
            id: time
            uses: nanzm/get-time-action@v1.1
            with:
              timeZone: 1
              format: 'YYYY-MM-DD-HH-mm-ss'

          - name: Create a zip of src
            uses: vimtor/action-zip@v1.1
            with:
              files: ${{ inputs.files}}
              recursive: false
              dest: ${{ inputs.output-name}}-${{ inputs.branch}}.zip

          - name: Create Release
            id: create_release
            uses: ncipollo/release-action@v1.12.0
            with:
              tag: ${{ inputs.output-name}}-${{ steps.time.outputs.time }}
              token: ${{ secrets.GITHUB_TOKEN }}
              name: ${{ inputs.output-name}}
              draft: false

          - name: Load zip as release
            id: upload-release-asset
            uses: softprops/action-gh-release@v1
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              files: ./${{ inputs.output-name}}-${{ inputs.branch}}.zip
              tag_name: ${{ inputs.output-name}}-${{ steps.time.outputs.time }}
